[tool.poetry]
name = "cca_zoo"
version = "0.0.0"
description = "Canonical Correlation Analysis Zoo: A collection of Regularized, Deep Learning based, Kernel, and Probabilistic methods in a scikit-learn style framework"
authors = ["jameschapman <james.chapman.19@ucl.ac.uk>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jameschapman19/cca_zoo"
keywords = ["cca"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.2"
scipy = "^1.9.2"
scikit-learn = "^1.2.2"
scikit-prox = "*"
matplotlib = "^3.5.1"
pandas = "^1.4.0"
seaborn = "^0.11.2"
tensorly = "^0.7.0"
joblib = "^1.2.2"
mvlearn = "^0.6.0"
tqdm = "^4.62.3"
torch = "^1.10.1"
pytorch-lightning = "^1.5.9"


[tool.poetry.dependencies.packages]
path = "."
develop = true

[tool.poetry.extras]
deep = ["torch", "torchvision", "pytorch-lightning"]
probabilistic = ["jax", "numpyro", "arviz"]
all = ["torch", "torchvision", "pytorch-lightning", "jax", "numpyro", "arviz"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
